require 'data_mapper'
require './app.rb'

namespace :db do
  desc 'Non destructive Upgrade'

  task :auto_upgrade do
    DataMapper.auto_upgrade!
    puts 'AutoUpgrade Complete'
  end

  task :auto_migrate do
    DataMapper.auto_migrate!
    puts 'AutoMigrate Complete'
  end
end
